### ISSUE TITLE
issuse when build  rocksdb 

### ISSUE THREAD

**Issue by ipconfiger** [rust-cross/rust-musl-cross#117] opened 2023-08-21 03:24 UTC
docker run --rm -it -v "$(pwd)":/home/rust/src messense/rust-musl-cross:x86_64-musl cargo build --release

`
process didn't exit successfully: `/home/rust/src/target/release/build/librocksdb-sys-801fddabdbc09a61/build-script-build` (exit status: 101)
  --- stderr
  /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
  thread 'main' panicked at 'unable to generate rocksdb bindings: ClangDiagnostic("/usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found\n")', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/librocksdb-sys-0.11.0+8.1.1/build.rs:40:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
`

but it success in 

docker run --rm -it -v "$(pwd)":/home/rust/src messense/rust-musl-cross:aarch64-musl cargo build --release

**Comment by messense** [comment] 2023-08-21 03:53
Maybe you can try this: https://github.com/rust-rocksdb/rust-rocksdb/issues/174#issuecomment-409410115

Since the upstream issue isn't closed yet, I'm closing this as not planned and duplicate of #45.

**Closed by messense** 2023-08-21 03:53 UTC
